name: lostcatithaca

services:
  caddy:
    build: .
    hostname: lostcatithaca
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - personal

volumes:
  caddy_data:
  caddy_config:

networks:
  personal:
    external: true
