# Generated by Django 3.2.4 on 2021-06-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
