# Generated by Django 3.2.4 on 2021-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0002_lostcat_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
