# Generated by Django 3.2.4 on 2021-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0003_alter_lostcat_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='image_exif_stripped',
            field=models.BooleanField(default=False),
        ),
    ]
