# Generated by Django 3.2.4 on 2021-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0004_lostcat_image_exif_stripped'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='slug',
            field=models.SlugField(default='slug', editable=False),
            preserve_default=False,
        ),
    ]
