# Generated by Django 3.2.4 on 2021-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0005_lostcat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostcat',
            name='image_exif_stripped',
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
