# Generated by Django 3.2.4 on 2021-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0006_auto_20210618_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcat',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
