# Generated by Django 3.2.4 on 2021-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0007_alter_lostcat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcat',
            name='slug',
            field=models.SlugField(),
        ),
    ]
