# Generated by Django 3.2.4 on 2021-06-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0008_alter_lostcat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='resized_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
