# Generated by Django 3.2.4 on 2021-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0009_lostcat_resized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcat',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
