# Generated by Django 3.2.4 on 2021-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostcats', '0010_alter_lostcat_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostcat',
            options={'ordering': ['-created']},
        ),
    ]
