# Generated by Django 3.2.4 on 2021-06-04 19:34

from django.db import migrations, models
import lostcats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(validators=[lostcats.models.validate_coordinate_global_limit])),
                ('longitude', models.FloatField(validators=[lostcats.models.validate_coordinate_global_limit])),
                ('image', models.ImageField(upload_to=lostcats.models.lost_cat_image_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
